version: '3.7'

services:
  userwebserver:
    image: userwebserver
    ports:
      - 80:80

  userwebclient:
    image: userwebclient
    ports:
      - 8000:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

